#
# Macro file for "Activation.cc"
#
/control/verbose 2
/run/verbose 2
#
/run/initialize
#
/process/list
#
/gun/particle deuteron
/gun/energy 500 keV
/testhadr/gun/beamSize 16 mm # target 2*radius
#/testhadr/gun/beamTime 10 year
#
/analysis/setFileName hist
/analysis/h1/set 4  600  0  18   MeV	#gamma
/analysis/h1/set 5  600  0  18   MeV	#gamma
/analysis/h1/set 6  600  0  18   MeV	#gamma
/analysis/h1/set 7  600  0  18   MeV	#gamma
/analysis/h1/set 8  600  0  18   MeV	#gamma
/analysis/h1/set 9  600  0  18   MeV	#gamma
/analysis/h1/set 10 600  0  18   MeV	#gamma

#/analysis/h1/set 14 600  0 20  year #gamma
#/analysis/h1/set 24 600  0 20  year
#/analysis/h1/set 25 600  0 20  year
#/analysis/h1/set 26 600  0 20  year
#
/run/printProgress 10000

/run/beamOn 5000
#/run/beamOn 1
#/run/beamOn 2
